SELECT TOP (1000) [AnnouncementID]
      ,[OfferingID]
      ,[PostedBy]
      ,[Title]
      ,[Content]
      ,[Priority]
      ,[IsActive]
      ,[CreatedAt]
  FROM [Flex_2].[dbo].[Announcements]
